
tasks:
  - init: |
      pushd myapp 
      npm install

    command: |
      export NUXT_TELEMETRY_DISABLED=1
      npm run dev

ports:
 - port: 3000
   onOpen: open-browser
 - port: 24678
   onOpen: ignore
